# PROJECT_ROOT is set by rootutils from the location of .project-root
root_dir: ${oc.env:PROJECT_ROOT}
data_dir: ${paths.root_dir}/data/
log_dir: ${paths.root_dir}/logs/
# created by hydra, see configs/hydra/default.yaml; checkpoints and samples go here
output_dir: ${hydra:runtime.output_dir}
work_dir: ${hydra:runtime.cwd}
